Repository Jij-Inc/ommx, pull requests merged in 2025-02, with the labels that each got.

#280 Deprecate `feasible_unrelaxed` in `*.proto`, and introduce `feasible_relaxed`
  proto/ommx/v1/sample_set.proto
  proto/ommx/v1/solution.proto
  python/ommx/ommx/v1/__init__.py
  python/ommx/ommx/v1/sample_set_pb2.py
  python/ommx/ommx/v1/sample_set_pb2.pyi
  python/ommx/ommx/v1/solution_pb2.py
  python/ommx/ommx/v1/solution_pb2.pyi
  rust/ommx/src/convert/sample_set.rs
  rust/ommx/src/evaluate.rs
  rust/ommx/src/ommx.v1.rs
  rust/protogen/src/main.rs
Labels: proto

#288 Release note for Python SDK 1.7.0
  docs/en/_toc.yml
  docs/en/ommx_message/sample_set.ipynb
  docs/en/release_note/ommx-1.6.0.ipynb
  docs/en/release_note/ommx-1.7.0.ipynb
  docs/en/tutorial/tsp_sampling_with_openjij_adapter.ipynb
  docs/ja/_toc.yml
  docs/ja/ommx_message/sample_set.ipynb
  docs/ja/release_note/ommx-1.5.0.ipynb
  docs/ja/release_note/ommx-1.6.0.ipynb
  docs/ja/release_note/ommx-1.7.0.ipynb
  docs/ja/tutorial/tsp_sampling_with_openjij_adapter.ipynb
  docs/pyproject.toml
  requirements.txt
Labels: documentation

#296 Enhance Documentation for docs/en/tutorial/download_miplib_instance.ipynb
  docs/en/tutorial/download_miplib_instance.ipynb
Labels: documentation

#294 Enhance Documentation for docs/en/tutorial/solve_with_ommx_adapter.ipynb
  docs/en/tutorial/solve_with_ommx_adapter.ipynb
Labels: documentation

#308 HotFix: bump up minimum `ommx` version to 1.8.1 in adapters using `ommx.adapter.SolverAdapter`
  python/ommx-pyscipopt-adapter/pyproject.toml
  python/ommx-python-mip-adapter/pyproject.toml
Labels: bug

#304 Enhance Documentation for docs/en/ommx message/sample_set
  docs/en/ommx_message/sample_set.ipynb
  docs/ja/ommx_message/sample_set.ipynb
Labels: documentation

#306 Enhance Documentation for docs/en/ommx_message/function.ipynb
  docs/en/ommx_message/function.ipynb
Labels: documentation

#305 Enhance Documentation for docs/en/ommx_message/instance.ipynb
  docs/en/ommx_message/instance.ipynb
Labels: documentation

#297 OMMX Message/Artifact design
  Taskfile.yml
  docs/en/_toc.yml
  docs/en/concept/architecture.ipynb
  docs/en/introduction.ipynb
  docs/en/introduction.md
  docs/en/ommx_artifact/architecture.ipynb
  docs/en/ommx_ecosystem/links.ipynb
  docs/en/user_guide/architecture.ipynb
  docs/en/user_guide/function.ipynb
  docs/en/user_guide/instance.ipynb
  docs/en/user_guide/sample_set.ipynb
  docs/en/user_guide/solution.ipynb
  docs/en/user_guide/solver_adapter.ipynb
  docs/ja/_toc.yml
  docs/ja/concept/architecture.ipynb
  docs/ja/introduction.ipynb
  docs/ja/introduction.md
  docs/ja/ommx_artifact/architecture.ipynb
  docs/ja/ommx_ecosystem/links.ipynb
  docs/ja/ommx_message/architecture.ipynb
  docs/ja/user_guide/function.ipynb
  docs/ja/user_guide/instance.ipynb
  docs/ja/user_guide/sample_set.ipynb
  docs/ja/user_guide/solution.ipynb
  docs/ja/user_guide/solver_adapter.ipynb
  docs/redirect/en/ommx_artifact/architecture.html
  docs/redirect/en/ommx_ecosystem/links.html
  docs/redirect/en/ommx_ecosystem/solver_adapter_guide.html
  docs/redirect/en/ommx_message/architecture.html
  docs/redirect/en/ommx_message/function.html
  docs/redirect/en/ommx_message/instance.html
  docs/redirect/en/ommx_message/solution.html
  docs/redirect/ja/ommx_artifact/architecture.html
  docs/redirect/ja/ommx_ecosystem/links.html
  docs/redirect/ja/ommx_ecosystem/solver_adapter_guide.html
  docs/redirect/ja/ommx_message/architecture.html
  docs/redirect/ja/ommx_message/function.html
  docs/redirect/ja/ommx_message/instance.html
  docs/redirect/ja/ommx_message/solution.html
Labels: documentation

#177 Adding Documentation for Sharing Data in OMMX Artifact
  docs/en/_toc.yml
  docs/en/tutorial/share_in_ommx_artifact.ipynb
  docs/ja/_toc.yml
  docs/ja/tutorial/share_in_ommx_artifact.ipynb
Labels: documentation

#319 Initializers for `Parameter` and `ParametricInstance`
  python/ommx/ommx/v1/__init__.py
Labels: python

#295 Enhance Documentation for docs/en/tutorial/tsp_sampling_with_openjij_adapter.ipynb
  docs/en/tutorial/tsp_sampling_with_openjij_adapter.ipynb
Labels: documentation

#323 Revise ommx.v1.ParametricInstnace
  docs/en/user_guide/architecture.ipynb
  docs/en/user_guide/parametric_instance.ipynb
Labels: documentation

#330 `ommx::random` submodule, `proptest::Arbitrary`-based random object generation
  Cargo.lock
  Cargo.toml
  rust/ommx/Cargo.toml
  rust/ommx/examples/create_artifact.rs
  rust/ommx/src/convert.rs
  rust/ommx/src/convert/constraint.rs
  rust/ommx/src/convert/decision_variable.rs
  rust/ommx/src/convert/format.rs
  rust/ommx/src/convert/function.rs
  rust/ommx/src/convert/instance.rs
  rust/ommx/src/convert/linear.rs
  rust/ommx/src/convert/parameter.rs
  rust/ommx/src/convert/parametric_instance.rs
  rust/ommx/src/convert/polynomial.rs
  rust/ommx/src/convert/quadratic.rs
  rust/ommx/src/convert/state.rs
  rust/ommx/src/evaluate.rs
  rust/ommx/src/lib.rs
  rust/ommx/src/random.rs
  rust/ommx/src/random/constraint.rs
  rust/ommx/src/random/decision_variable.rs
  rust/ommx/src/random/function.rs
  rust/ommx/src/random/instance.rs
  rust/ommx/src/random/linear.rs
  rust/ommx/src/random/parameter.rs
  rust/ommx/src/random/parametric_instance.rs
  rust/ommx/src/random/polynomial.rs
  rust/ommx/src/random/quadratic.rs
  rust/ommx/src/random/state.rs
  rust/ommx/src/sorted_ids.rs
Labels: rust

#333 Revise `Parameters` in `Arbitrary` trait
  rust/ommx/examples/create_artifact.rs
  rust/ommx/src/convert/function.rs
  rust/ommx/src/convert/instance.rs
  rust/ommx/src/convert/linear.rs
  rust/ommx/src/convert/polynomial.rs
  rust/ommx/src/lib.rs
  rust/ommx/src/mps/tests.rs
  rust/ommx/src/random.rs
  rust/ommx/src/random/constraint.rs
  rust/ommx/src/random/decision_variable.rs
  rust/ommx/src/random/function.rs
  rust/ommx/src/random/instance.rs
  rust/ommx/src/random/linear.rs
  rust/ommx/src/random/parametric_instance.rs
  rust/ommx/src/random/polynomial.rs
  rust/ommx/src/random/quadratic.rs
Labels: rust
